import React from 'react';
import LegalPage, { H2, H3, P, UL } from './LegalPage';

const PrivacyPolicy = () => (
  <LegalPage title="Privacy Policy" updated="July 8, 2026">
    <P>
      This Privacy Policy explains how Post-To ("Post-To", "we", "us", "our") collects,
      uses, and safeguards information when you use our AI marketing platform for local
      businesses (the "Service"). By using the Service, you agree to this policy.
    </P>

    <H2>1. Information we collect</H2>

    <H3>1.1 Account information</H3>
    <P>
      When you sign in with Google, we receive your name, email address, profile picture,
      and a unique Google user identifier. We store this to identify you across sessions.
    </P>

    <H3>1.2 Business data you connect</H3>
    <P>
      Post-To reads data from third-party services you choose to connect. Depending on which
      integrations you enable, this may include:
    </P>
    <UL>
      <li>
        <strong>Google Business Profile:</strong> business name, address, categories, hours,
        services, posts, photos, reviews, and performance metrics (search views, calls,
        direction requests).
      </li>
      <li>
        <strong>Google Analytics 4:</strong> read-only property, dimensions, and metrics
        including sessions, users, traffic sources, landing pages, events, campaigns,
        devices, and geography.
      </li>
      <li>
        <strong>Your website:</strong> publicly available page content (title, description,
        Open Graph tags, on-page text) used to learn your business voice and services.
      </li>
      <li>
        <strong>Social channels (Instagram, Facebook, LinkedIn, X, WordPress):</strong>
        account identifiers and content necessary to publish posts on your behalf.
      </li>
    </UL>

    <H3>1.3 Content you create</H3>
    <P>
      Drafts, published posts, review replies, blog articles, and any content generated by
      our AI on your behalf.
    </P>

    <H3>1.4 Technical data</H3>
    <P>
      IP address, browser type, device information, page views, and request logs. We use
      these for security, rate limiting, and debugging.
    </P>

    <H2>2. How we use information</H2>
    <UL>
      <li>Operate, maintain, and improve the Service.</li>
      <li>Learn your business voice, services, and audience so the AI can generate relevant marketing content.</li>
      <li>Publish, schedule, and monitor content on channels you have connected.</li>
      <li>Surface analytics and recommendations tailored to your business.</li>
      <li>Send transactional emails (billing, security alerts, product updates).</li>
      <li>Detect abuse, prevent fraud, and enforce our Terms of Service.</li>
      <li>Comply with legal obligations.</li>
    </UL>

    <H2>3. AI processing</H2>
    <P>
      To generate content, we send relevant portions of your connected data (e.g. reviews,
      services, prior posts) to third-party AI providers such as OpenAI. We do not send more
      than is necessary to fulfill your request, and we do not permit these providers to use
      your data to train their public models.
    </P>

    <H2>4. Google API user data</H2>
    <P>
      Post-To's use and transfer of information received from Google APIs adheres to the
      <a href="https://developers.google.com/terms/api-services-user-data-policy" target="_blank" rel="noreferrer" className="text-primary-600 hover:underline"> Google API Services User Data Policy</a>,
      including the Limited Use requirements. In particular:
    </P>
    <UL>
      <li>We only use Google user data to provide user-facing features of the Service.</li>
      <li>We do not sell Google user data.</li>
      <li>We do not use Google user data for advertising.</li>
      <li>We do not allow humans to read Google user data unless you have given explicit consent, it is required for security, we are legally compelled, or the data has been aggregated and anonymized for internal operations.</li>
    </UL>
    <P>
      You can revoke Post-To's access to your Google account at any time via{' '}
      <a href="https://myaccount.google.com/permissions" target="_blank" rel="noreferrer" className="text-primary-600 hover:underline">
        myaccount.google.com/permissions
      </a>.
    </P>

    <H2>5. Sharing information</H2>
    <P>We share information only in the following circumstances:</P>
    <UL>
      <li>
        <strong>Service providers</strong> that help us run Post-To (cloud hosting, database,
        analytics, error monitoring, AI providers, payment processing). Each is contractually
        bound to protect your data.
      </li>
      <li>
        <strong>Connected platforms</strong> — when you publish content, we transmit that
        content to the destination platform you selected.
      </li>
      <li>
        <strong>Legal compliance</strong> — where required by law, subpoena, or a valid
        government request.
      </li>
      <li>
        <strong>Business transfers</strong> — in connection with a merger, acquisition, or
        sale of assets. You will be notified before your data becomes subject to a different
        privacy policy.
      </li>
    </UL>
    <P>We do not sell your personal information.</P>

    <H2>6. Data retention</H2>
    <P>
      We retain your data while your account is active. If you delete your account, we
      remove your personal information within 30 days, except where retention is required
      for legal, tax, or fraud-prevention purposes. Anonymous aggregated data may be kept
      indefinitely.
    </P>

    <H2>7. Security</H2>
    <P>
      We use industry-standard measures — encryption in transit (TLS 1.2+), encrypted
      storage, scoped access tokens, role-based access controls, and independent security
      reviews. No system is perfectly secure, but we work continuously to protect your data.
    </P>

    <H2>8. Your rights</H2>
    <P>
      Depending on where you live, you may have the right to access, correct, export, or
      delete your personal information, and to object to or restrict certain processing.
      Email us at{' '}
      <a href="mailto:privacy@post-to.app" className="text-primary-600 hover:underline">privacy@post-to.app</a>
      {' '}to exercise these rights. We respond within 30 days.
    </P>

    <H2>9. Children</H2>
    <P>
      Post-To is not directed to individuals under 16. We do not knowingly collect data from
      children. If you believe a child has provided us data, contact us and we will delete it.
    </P>

    <H2>10. International transfers</H2>
    <P>
      Your data may be processed in the United States or other countries where our service
      providers operate. Where required, we rely on standard contractual clauses to protect
      data transferred internationally.
    </P>

    <H2>11. Changes to this policy</H2>
    <P>
      We may update this policy from time to time. Material changes will be announced in the
      product and by email. Continued use of the Service after the effective date constitutes
      acceptance.
    </P>

    <H2>12. Contact</H2>
    <P>
      Questions about this policy? Email{' '}
      <a href="mailto:privacy@post-to.app" className="text-primary-600 hover:underline">
        privacy@post-to.app
      </a>.
    </P>
  </LegalPage>
);

export default PrivacyPolicy;
